fix: lvalue required as unary '&' operand
Don't seem like JANA2 actually relies on those semantics.

In file included from /build/source/src/programs/unit_tests/PodioTests.cc:2:
/build/source/src/programs/unit_tests/PodioTests.cc: In function 'void podiotests::____C_A_T_C_H____T_E_S_T____6()':
/build/source/src/programs/unit_tests/PodioTests.cc:61:27: error: lvalue required as unary '&' operand
   61 |         REQUIRE(&(a.energy()) == &(b.energy())); // energy() getter returns a const& into the actual data object
      |                  ~~~~~~~~~^~~
/build/source/src/programs/unit_tests/PodioTests.cc:61:44: error: lvalue required as unary '&' operand
   61 |         REQUIRE(&(a.energy()) == &(b.energy())); // energy() getter returns a const& into the actual data object
      |                                   ~~~~~~~~~^~~